alias ll='ls -AhlF --color=auto'
alias la='ls -Ah --color=auto'
alias l='ls -AhlF --color=auto'
alias ls='ls -l --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
